XVST ; Paideia/SMH - VPE handle timeout ; 10/18/09 12:29am
 ;;13.1;VICTORY PROG ENVIRONMENT;;May 23, 2016
 S XVVSHC=$G(^XVEMS("QU",XVV("ID"),"TO"))
 Q:XVVSHC=""
 S:XVVSHC="HALT"!(XVVSHC="halt") XVVSHC="^"
